#!/bin/bash

# Define the path to your dotfiles directory
dotfiles_dir=~/Documents/Dotfiles

# List of dotfiles to symlink
declare -a files_to_symlink=(".vimrc" ".tmux.conf" ".condarc")

# Loop through the list and create symlinks
for file in "${files_to_symlink[@]}"; do
  # Destination path for the symlink
  dest=~/$(basename "$file")

  # Check if the destination file exists as a regular file or symlink
  if [ -e "$dest" ] || [ -L "$dest" ]; then
    # File exists (either as a regular file or a symlink)
    echo "Warning: $dest already exists. Skipping..."
  else
    # Create the symlink
    ln -s "$dotfiles_dir/$file" "$dest"
    echo "Symlink created for $file"
  fi
done

# Note about Neovim configuration
echo "Note: For Neovim configuration, please refer to the LazyVim official repository."

echo "All configurations have been processed."
